# Generated by Django 2.2.4 on 2019-10-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_review', models.CharField(max_length=3)),
                ('movie_release_date', models.CharField(max_length=20)),
                ('movie_type', models.CharField(max_length=50)),
                ('movie_detail', models.TextField(max_length=500)),
                ('movie_info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MovieInfo_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_test', models.CharField(max_length=200)),
            ],
        ),
    ]
