# Generated by Django 2.2.4 on 2019-11-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_movieinfo_movieinfo_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='MovieInfo',
        ),
        migrations.DeleteModel(
            name='MovieInfo_Test',
        ),
    ]
