# Generated by Django 2.2.4 on 2019-11-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_post_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='videofile',
            field=models.FileField(null=True, upload_to='haha/', verbose_name=''),
        ),
    ]
