# Generated by Django 2.2.4 on 2019-11-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20191122_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='videofile',
            field=models.FileField(null=True, upload_to='posts/', verbose_name=''),
        ),
    ]
