# Generated by Django 2.2.4 on 2019-11-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20191122_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='videofile',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=777, max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
