# Generated by Django 2.2.4 on 2019-11-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20191122_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
