# Generated by Django 2.2.4 on 2020-02-23 05:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200220_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='theBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The number of the base based on video number (e.g. Base1)', max_length=500)),
                ('check1', models.TextField(default=None, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('check2', models.TextField(default=None, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('check3', models.TextField(default=None, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('check4', models.TextField(default=None, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('check5', models.TextField(default=None, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('check6', models.TextField(default=None, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('check7', models.TextField(default=None, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('check8', models.TextField(default=None, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('check9', models.TextField(default=None, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('check10', models.TextField(default=None, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)])),
                ('check11', models.TextField(default=None, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)])),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Sign',
        ),
        migrations.RemoveField(
            model_name='video',
            name='videofile',
        ),
        migrations.AddField(
            model_name='video',
            name='location',
            field=models.CharField(default=None, help_text='folder location in the server', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular video across whole database', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(help_text='The number of the video (e.g. Video1)', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='MLresults',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.theBase'),
        ),
    ]
