# Generated by Django 2.2.4 on 2020-02-23 05:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20200223_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular video across whole database', primary_key=True, serialize=False, unique=True),
        ),
    ]
