# Generated by Django 2.2.4 on 2020-02-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_thebase_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='location',
            field=models.CharField(default=None, help_text='folder location in the server (e.g. media/1)', max_length=500),
        ),
    ]
