# Generated by Django 2.2.4 on 2020-02-23 06:08

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20200223_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thebase',
            name='results',
            field=models.CharField(default=None, help_text='ML check results here (e.g. "6 5 11 1 10")', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
