# Generated by Django 2.2.4 on 2020-02-23 06:13

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20200223_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thebase',
            name='check1',
            field=models.TextField(blank=True, default=None, help_text='Do not touch, check results here in form "1 0 0 1 1 0 1', null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='thebase',
            name='check10',
            field=models.TextField(blank=True, default=None, help_text='Do not touch, check results here in form "1 0 0 1 1 0 1', null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='thebase',
            name='check11',
            field=models.TextField(blank=True, default=None, help_text='Do not touch, check results here in form "1 0 0 1 1 0 1', null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='thebase',
            name='check2',
            field=models.TextField(blank=True, default=None, help_text='Do not touch, check results here in form "1 0 0 1 1 0 1', null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='thebase',
            name='check3',
            field=models.TextField(blank=True, default=None, help_text='Do not touch, check results here in form "1 0 0 1 1 0 1', null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='thebase',
            name='check4',
            field=models.TextField(blank=True, default=None, help_text='Do not touch, check results here in form "1 0 0 1 1 0 1', null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='thebase',
            name='check5',
            field=models.TextField(blank=True, default=None, help_text='Do not touch, check results here in form "1 0 0 1 1 0 1', null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='thebase',
            name='check6',
            field=models.TextField(blank=True, default=None, help_text='Do not touch, check results here in form "1 0 0 1 1 0 1', null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='thebase',
            name='check7',
            field=models.TextField(blank=True, default=None, help_text='Do not touch, check results here in form "1 0 0 1 1 0 1', null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='thebase',
            name='check8',
            field=models.TextField(blank=True, default=None, help_text='Do not touch, check results here in form "1 0 0 1 1 0 1', null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='thebase',
            name='check9',
            field=models.TextField(blank=True, default=None, help_text='Do not touch, check results here in form "1 0 0 1 1 0 1', null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='thebase',
            name='results',
            field=models.CharField(blank=True, default=None, help_text='ML check results here (e.g. "6 5 11 1 10")', max_length=500, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
