# Generated by Django 2.2.4 on 2020-02-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20200223_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='numberOfVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='The number of the videos in the Database', max_length=500)),
            ],
        ),
    ]
