# Generated by Django 2.2.4 on 2020-02-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20200223_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='text',
            field=models.CharField(default=1, help_text='Which text was demonstrated on video (e.g. "1")', max_length=500),
            preserve_default=False,
        ),
    ]
