# Generated by Django 2.2.4 on 2020-02-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thebase',
            name='usersprovided',
            field=models.TextField(blank=True, default=None, help_text='Users that provided the check results', null=True),
        ),
    ]
