# Generated by Django 2.2.4 on 2020-02-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_thebase_usersprovided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thebase',
            name='usersprovided',
            field=models.TextField(blank=True, default='', help_text='Users that provided the check results', null=True),
        ),
    ]
